# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_newslink_unique_together_slug_startup'),
    ]

    operations = [
    ]
